# Generated by Django 4.2.6 on 2023-11-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdat')),
                ('modifiedAt', models.DateTimeField(auto_now=True, verbose_name='modifiedat')),
                ('isDeleted', models.BooleanField(default=False, verbose_name='isdeleted')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='issuperuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
