# Generated by Django 4.2.6 on 2023-11-13 12:42

from django.db import migrations
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user_management.models.CustomManager()),
            ],
        ),
    ]
